In [23]:
import numpy as np
from collections import defaultdict

In [24]:
# 1 means acessible. 0 means not inaccessible

floor = np.array([[1, 1, 0, 0], [1, 0, 0, 1], [1, 1, 1, 1], [0, 0, 1, 1]])
print (floor)

[[1 1 0 0]
 [1 0 0 1]
 [1 1 1 1]
 [0 0 1 1]]


In [25]:
# Approach #2: more concise approach

def generate_graph(matrix):
    '''
    Simplified approach to generate graph
    '''
    height = matrix.shape[0]
    width = matrix.shape[1]
    graph = defaultdict(set)
    for i in range(height):
        for j in range(width):
            neighbours = [[i, j-1], [i, j+1], [i-1, j], [i+1, j]]
            for k in neighbours:
                if 0<=k[0]<height and 0<=k[1]<width:
                    if matrix[k[0]][k[1]] == 1:
                        graph[(i, j)].add((k[0],k[1]))
    return graph

In [26]:
def identify_route(graph, start_point, end_point):
    visited = set()
    route = set()
    stack = []
    stack.append(start_point)
    
    while stack:
        curr_vertex = stack.pop()
        visited.add(curr_vertex)
        route.add(curr_vertex)
        if curr_vertex == end_point:
            break
        for vertex in graph[curr_vertex]:
            if vertex not in visited:
                stack.append(vertex)
    return route

In [104]:
def all_routes(route, next_vertex, end_vertex, graph, res):
    # route keeps track of single route
    # res keeps tracks of all routes
    
    if next_vertex == end_vertex:
        res.append(route)
        return res
#     elif len(next_vertex) == 0 and :
#         return res
    else:
        for vertex in graph[next_vertex]:
            if vertex not in route:
                route.append(vertex)
                all_routes(route, vertex, end_vertex, graph, res)
    return res

In [105]:
graph = generate_graph(floor)
graph

defaultdict(set,
            {(0, 0): {(0, 1), (1, 0)},
             (0, 1): {(0, 0)},
             (0, 2): {(0, 1)},
             (0, 3): {(1, 3)},
             (1, 0): {(0, 0), (2, 0)},
             (1, 1): {(0, 1), (1, 0), (2, 1)},
             (1, 2): {(1, 3), (2, 2)},
             (1, 3): {(2, 3)},
             (2, 0): {(1, 0), (2, 1)},
             (2, 1): {(2, 0), (2, 2)},
             (2, 2): {(2, 1), (2, 3), (3, 2)},
             (2, 3): {(1, 3), (2, 2), (3, 3)},
             (3, 0): {(2, 0)},
             (3, 1): {(2, 1), (3, 2)},
             (3, 2): {(2, 2), (3, 3)},
             (3, 3): {(2, 3), (3, 2)}})

In [106]:
identify_route(graph, (0,0), (3,3))

{(0, 0), (1, 0), (2, 0), (2, 1), (2, 2), (2, 3), (3, 3)}

In [107]:
route = []
res = []
route.append((0,0))

all_routes(route, (0,0), (3,3),graph, res)

[[(0, 0),
  (0, 1),
  (1, 0),
  (2, 0),
  (2, 1),
  (2, 2),
  (3, 2),
  (3, 3),
  (2, 3),
  (1, 3)]]